In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train = pd.read_csv('datasets/Training.csv')

In [5]:
train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [9]:
train.prognosis.value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
All

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [13]:
X = train.drop('prognosis',axis=1)
y = train['prognosis']

In [17]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=69)

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

models = {
    "SVC": SVC(kernel='rbf', C=1.0, gamma='scale'),
    "RandomForest": RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42, criterion='gini'),
    "GradientBoogsting": GradientBoostingClassifier(n_estimators=150, learning_rate=0.1, max_depth=3, random_state=42),
    "KNeighbors": KNeighborsClassifier(n_neighbors=7, weights='uniform', metric='minkowski'),
    "MultinomialNB": MultinomialNB(alpha=1.0, fit_prior=True)
}

In [40]:
for model_name,model in models.items():
    model.fit(X_train,y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test,pred)
    cm = confusion_matrix(y_test,pred)
    print(f'model : {model_name} and accuracy : {acc}')
    print(cm)

model : SVC and accuracy : 1.0
[[42  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 33]]
model : RandomForest and accuracy : 1.0
[[42  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 33]]
model : GradientBoosting and accuracy : 1.0
[[42  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 33]]
model : KNeighbors and accuracy : 1.0
[[42  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 33]]
model : MultinomialNB and accuracy : 1.0
[[42  0  0 ...  0  0  0]
 [ 0 46  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 33]]


In [46]:
svc = SVC(kernel='rbf',C=1.0,gamma='scale')
svc.fit(X_train,y_train)
pred = svc.predict(X_test)
accuracy_score(y_test,pred)

1.0

In [52]:
import pickle
import os
os.makedirs('models',exist_ok=True)
pickle.dump(svc,open("models/svc.pkl",'wb'))

In [103]:
rf = RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42, criterion='gini')
rf.fit(X_train,y_train)
pred = rf.predict(X_test)
accuracy_score(y_test,pred)

1.0

In [105]:
pickle.dump(rf,open("models/rf.pkl",'wb'))

In [54]:
sym_des = pd.read_csv('datasets/symtoms_df.csv')

In [56]:
sym_des.head()

Unnamed: 0           Disease   Symptom_1              Symptom_2  \
0           0  Fungal infection     itching              skin_rash   
1           1  Fungal infection   skin_rash   nodal_skin_eruptions   
2           2  Fungal infection     itching   nodal_skin_eruptions   
3           3  Fungal infection     itching              skin_rash   
4           4  Fungal infection     itching              skin_rash   

               Symptom_3             Symptom_4  
0   nodal_skin_eruptions   dischromic _patches  
1    dischromic _patches                   NaN  
2    dischromic _patches                   NaN  
3    dischromic _patches                   NaN  
4   nodal_skin_eruptions                   NaN

In [77]:
precautions = pd.read_csv('datasets/precautions_df.csv')
workout = pd.read_csv('datasets/workout_df.csv')
description = pd.read_csv('datasets/description.csv')
medications = pd.read_csv('datasets/medications.csv')
diets = pd.read_csv('datasets/diets.csv')

In [85]:
symptoms = {}
for i,j in enumerate(X_train.columns.tolist()):
    symptoms[j] = i

In [87]:
symptoms

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

In [99]:
diseases = dict(zip(range(len(le.classes_)), le.classes_))

In [101]:
diseases

{0: '(vertigo) Paroymsal  Positional Vertigo',
 1: 'AIDS',
 2: 'Acne',
 3: 'Alcoholic hepatitis',
 4: 'Allergy',
 5: 'Arthritis',
 6: 'Bronchial Asthma',
 7: 'Cervical spondylosis',
 8: 'Chicken pox',
 9: 'Chronic cholestasis',
 10: 'Common Cold',
 11: 'Dengue',
 12: 'Diabetes ',
 13: 'Dimorphic hemmorhoids(piles)',
 14: 'Drug Reaction',
 15: 'Fungal infection',
 16: 'GERD',
 17: 'Gastroenteritis',
 18: 'Heart attack',
 19: 'Hepatitis B',
 20: 'Hepatitis C',
 21: 'Hepatitis D',
 22: 'Hepatitis E',
 23: 'Hypertension ',
 24: 'Hyperthyroidism',
 25: 'Hypoglycemia',
 26: 'Hypothyroidism',
 27: 'Impetigo',
 28: 'Jaundice',
 29: 'Malaria',
 30: 'Migraine',
 31: 'Osteoarthristis',
 32: 'Paralysis (brain hemorrhage)',
 33: 'Peptic ulcer diseae',
 34: 'Pneumonia',
 35: 'Psoriasis',
 36: 'Tuberculosis',
 37: 'Typhoid',
 38: 'Urinary tract infection',
 39: 'Varicose veins',
 40: 'hepatitis A'}

In [309]:
def helper(dis):
    desc = description[description['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]
    med[0] = med[0].replace('[','').replace(']','').replace("'",'')
    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]
    die[0] = die[0].replace('[','').replace(']','').replace("'",'')
    wrkout = workout[workout['disease'] == dis]['workout']

    return desc, list(pre.values[0]), med[0].split(','), die[0].split(','), list(wrkout.values)
def predicted_value(patient_symptoms):
    inputs = np.zeros(len(symptoms))
    for item in patient_symptoms:
        inputs[symptoms[item]] = 1
    return diseases[rf.predict([inputs])[0]]

In [319]:
v,w,x,y,z = helper('Malaria')

In [338]:
import sklearn
sklearn.__version__

'1.5.1'